default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET
default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas" }
    methods: POST 
default_query:
    path: /query
    defaults: { _controller: "AppBundle:CategoriaAnimal:query" }
    methods: POST
default_edit:
    path: /edit
    defaults: { _controller: "AppBundle:CategoriaAnimal:edit" }
    methods: POST
default_new:
    path: /new
    defaults: { _controller: "AppBundle:CategoriaAnimal:new" }
    methods: POST
default_delete:
    path: /delete
    defaults: { _controller: "AppBundle:CategoriaAnimal:delete" }
    methods: POST