BackendBundle\Entity\Tcategoriaanimal:
    type: entity
    table: tcategoriaanimal
    id:
        pkidcategoriaanimal:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        nombrecategoriaanimal:
            type: string
            nullable: false
            length: 225
            options:
                fixed: false
        descripcioncategoriaanimal:
            type: string
            nullable: true
            length: 225
            options:
                fixed: false
        creacioncategoriaanimal:
            type: datetime
            nullable: false
            options:
                default: now()
        modificacioncategoriaanimal:
            type: datetime
            nullable: false
            options:
                default: now()
        categoriaanimalactivo:
            type: boolean
            nullable: false
            options:
                default: true
        codigocategoriaanimal:
            type: string
            nullable: true
            length: 225
            options:
                fixed: false
    lifecycleCallbacks: {  }
